// gen_vectors.c — emit C-computed parity vectors for the detector primitives.
//
// Runs the REAL detector.c primitives on a set of fixed, deterministic inputs
// and prints expected_vectors.json. The Python port in tools/onair-test/rig/
// separability.py is locked to these C-computed values by test_separability_
// parity.py, which gates every PR.
//
// The same fixed inputs are reproduced in the Python parity test; keep the two
// in sync. Inputs are generated by a tiny self-contained LCG (NOT ag_prng) so
// the vector definitions live entirely in this file and are trivially mirrored
// in Python.
//
//   build:  part of test/host CMake (target gen_vectors)
//   run:    ./gen_vectors > .../parity/expected_vectors.json
#include "../detector.h"
#include <stdint.h>
#include <stdio.h>

// A tiny, fully-specified LCG so the Python parity test can reproduce the exact
// same inputs without depending on any shared library. Numerical Recipes ranqd1.
static uint32_t g_state;
static void lcg_seed(uint32_t s) { g_state = s; }
static double lcg_unit(void)
{
    g_state = 1664525u * g_state + 1013904223u;
    return (double)g_state / 4294967296.0; // [0,1)
}
// uniform in [lo,hi)
static double lcg_uniform(double lo, double hi) { return lo + (hi - lo) * lcg_unit(); }

#define N 1500

static double a_rssi[N];
static double b_rssi[N];
static double a_gaps[N];
static double b_gaps[N];
static double pooled[2 * N];
static double small_set[8] = {-70, -71, -69, -70, -72, -68, -70, -71};
static double bimodal[10] = {-90, -91, -89, -90, -50, -49, -51, -50, -90, -50};

int main(void)
{
    // Build two RSSI streams with different but overlapping spreads, and two
    // jittered gap streams, from the fixed LCG.
    lcg_seed(0xC0FFEEu);
    double center = -68.0;
    for (int i = 0; i < N; i++) {
        a_rssi[i] = center + lcg_uniform(-6.0, 6.0);
        b_rssi[i] = center + lcg_uniform(-5.0, 5.0);
    }
    for (int i = 0; i < N; i++) {
        a_gaps[i] = 100.0 + lcg_uniform(-5.0, 5.0);
        b_gaps[i] = 100.0 + lcg_uniform(-4.0, 4.0);
    }
    for (int i = 0; i < N; i++) {
        pooled[i] = a_rssi[i];
        pooled[N + i] = b_rssi[i];
    }

    double ks = det_ks_statistic(a_rssi, N, b_rssi, N);
    double ks_crit = det_ks_critical_05(N, N);
    double ks_small = det_ks_statistic(small_set, 8, bimodal, 10);
    double ks_crit_small = det_ks_critical_05(8, 10);
    double cv_a = det_interval_regularity_cv(a_gaps, N);
    double cv_b = det_interval_regularity_cv(b_gaps, N);
    double cv_small = det_interval_regularity_cv(small_set, 8);
    double sd_a = det_rssi_stability(a_rssi, N);
    double sd_b = det_rssi_stability(b_rssi, N);
    double sd_small = det_rssi_stability(small_set, 8);
    double sep_pooled = det_two_means_separation(pooled, 2 * N);
    double sep_bimodal = det_two_means_separation(bimodal, 10);
    double sep_small = det_two_means_separation(small_set, 8);

    // Emit with full precision so the Python side can match tightly.
    printf("{\n");
    printf("  \"_note\": \"C-computed via detector.c; regenerate with gen_vectors\",\n");
    printf("  \"seed\": 12648430,\n");
    printf("  \"n\": %d,\n", N);
    printf("  \"ks_statistic\": %.17g,\n", ks);
    printf("  \"ks_critical_05\": %.17g,\n", ks_crit);
    printf("  \"ks_statistic_small\": %.17g,\n", ks_small);
    printf("  \"ks_critical_05_small\": %.17g,\n", ks_crit_small);
    printf("  \"interval_regularity_cv_a\": %.17g,\n", cv_a);
    printf("  \"interval_regularity_cv_b\": %.17g,\n", cv_b);
    printf("  \"interval_regularity_cv_small\": %.17g,\n", cv_small);
    printf("  \"rssi_stability_a\": %.17g,\n", sd_a);
    printf("  \"rssi_stability_b\": %.17g,\n", sd_b);
    printf("  \"rssi_stability_small\": %.17g,\n", sd_small);
    printf("  \"two_means_separation_pooled\": %.17g,\n", sep_pooled);
    printf("  \"two_means_separation_bimodal\": %.17g,\n", sep_bimodal);
    printf("  \"two_means_separation_small\": %.17g\n", sep_small);
    printf("}\n");
    return 0;
}
