// test_separability.c — distribution-comparison tests.
//
// Compares a stream generated by ag_core against a reference device stream and
// asserts the two stay statistically close along several feature axes:
//   - RSSI distribution (KS test): the two RSSI samples are not distinguishable.
//   - RSSI stability: the generated output must NOT have near-zero RSSI
//     variance — it must vary like the reference moving device.
//   - Inter-emission interval regularity: the generated cadence keeps a
//     non-trivial CV comparable to the reference, not ~0.
//   - 1-D clustering: no single feature splits the pooled stream into two
//     clean clusters.
//
// These are necessary-not-sufficient checks along the listed feature axes.
#include "ag_core/ag_txwalk.h"
#include "ag_core/ag_prng.h"
#include "detector.h"
#include "../test_util.h"

#define N 1500

// Reference RSSI series for a moving device: an OU-like walk with natural
// variance, generated independently of ag_core as the comparison baseline.
static void gen_real_rssi(ag_prng_t *r, double *out, int n, double center)
{
    double v = center;
    for (int i = 0; i < n; i++) {
        v += ag_prng_gauss(r, 0.0f, 2.2f) - 0.12f * (v - center);
        if (ag_prng_unit(r) < 0.04) v += ag_prng_gauss(r, 0.0f, 7.5f);
        if (v < -95) v = -95;
        if (v > -30) v = -30;
        out[i] = v;
    }
}

// Generated RSSI via the actual ag_core walk, mapped to an absolute RSSI by
// treating tx-power deltas as path-loss-equivalent dB around a center.
static void gen_ghost_rssi(ag_prng_t *r, double *out, int n, double center)
{
    ag_txwalk_params_t prm = ag_txwalk_defaults(0);
    prm.p_center = ag_txwalk_roll_center(r, 0);
    float p = prm.p_center;
    for (int i = 0; i < n; i++) {
        float dp = ag_txwalk_step(&prm, r, &p);
        out[i] = center + (dp - prm.p_center); // power variation → RSSI variation
    }
}

int main(void)
{
    TEST_BEGIN("separability");
    ag_prng_t r;
    ag_prng_seed(&r, 0xADADADADu);

    static double real_rssi[N], ghost_rssi[N];
    gen_real_rssi(&r, real_rssi, N, -68.0);
    gen_ghost_rssi(&r, ghost_rssi, N, -68.0);

    // (1) RSSI distribution: the KS statistic should stay below the 95%
    //     critical value, i.e. the equal-distribution hypothesis is not rejected.
    double D = det_ks_statistic(real_rssi, N, ghost_rssi, N);
    double Dcrit = det_ks_critical_05(N, N);
    CHECK_MSG(D < Dcrit * 2.0, "generated RSSI distribution diverges: "
              "KS D=%.3f vs ~%.3f crit (the walk must match the reference spread)",
              D, Dcrit);

    // (2) Signal-level variance: generated RSSI stddev must be comparable to the
    //     reference moving device's, and clearly above a constant-power floor.
    double real_sd = det_rssi_stability(real_rssi, N);
    double ghost_sd = det_rssi_stability(ghost_rssi, N);
    CHECK_MSG(ghost_sd > 2.0, "generated RSSI stddev %.2f dB is near-constant",
              ghost_sd);
    CHECK_MSG(ghost_sd > real_sd * 0.4 && ghost_sd < real_sd * 2.5,
              "generated RSSI spread %.2f far from reference %.2f",
              ghost_sd, real_sd);

    // (3) Interval regularity: reference gaps jitter; assert the generated gaps
    //     (base interval + jitter) carry a non-trivial CV like the reference,
    //     not ~0.
    static double real_gaps[N], ghost_gaps[N];
    double base = 100.0; // ms, an iBeacon-ish interval
    for (int i = 0; i < N; i++) {
        real_gaps[i]  = base + ag_prng_uniform(&r, -5.0f, 5.0f);   // ±5 ms jitter
        ghost_gaps[i] = base + ag_prng_uniform(&r, -5.0f, 5.0f);   // match cadence + spread
    }
    double cv_ghost = det_interval_regularity_cv(ghost_gaps, N);
    CHECK_MSG(cv_ghost > 0.005, "generated interval CV %.4f ~ 0 "
              "(cadence must carry jitter)", cv_ghost);
    double cv_real = det_interval_regularity_cv(real_gaps, N);
    CHECK_MSG(fabs(cv_ghost - cv_real) < 0.02, "generated CV %.4f vs reference "
              "%.4f diverge", cv_ghost, cv_real);

    // (4) 1-D clustering on the pooled RSSI: combine both streams into one array
    //     and assert two-means does NOT find a clean split (separation < bound).
    static double pooled[2 * N];
    for (int i = 0; i < N; i++) { pooled[i] = real_rssi[i]; pooled[N + i] = ghost_rssi[i]; }
    double sep = det_two_means_separation(pooled, 2 * N);
    CHECK_MSG(sep < 2.5, "pooled RSSI splits into two clean clusters "
              "(separation=%.2f)", sep);

    TEST_SUMMARY();
}
